services:
  postgres:
    image: postgres:16
    container_name: inv_pg
    environment:
      POSTGRES_DB: invdb
      POSTGRES_USER: invuser
      POSTGRES_PASSWORD: invpass
    ports:
      - "5432:5432"
    volumes:
      - inv_pg_data:/var/lib/postgresql/data
volumes:
  inv_pg_data:
    